### ISSUE TITLE
Tests and Python Dependencies

### ISSUE THREAD

**Issue by thazhemadam** [SimonEnsemble/Xtals.jl#122]
Presently, the tests seem to be broken. The CI seems to be selectively testing only some parts, and hence seems to pass. Meanwhile, running `] test` shows that tests don't pass. Is there any reason behind this? I can add a workflow that tests everything if required.

One of the reasons the tests seems to be broken is because -
```julia
NiPyC2 Tests: Error During Test at /home/runner/work/Xtals.jl/Xtals.jl/test/bonds.jl:139
  Got exception outside of a @test
  Python dependency scipy not loaded.
```
I'm a little confused here, I thought Xtals was a pure-Julia package (as mentioned in the README). Then why is not having a Python dependency breaking tests?

**Comment by eahenle** [comment]
The CI runner builds the python deps first.  The CI is only selective, so far as I'm aware, when testing if `Xtals` has a breaking change for a couple of key projects within our group, `PorousMaterials` and `PoreMatMod`.  Failing that test doesn't mean we should block a merge, but we want a warning that those packages will need patching.

`scipy` enables the function `infer_geometry_based_bonds!`.  That code predates me on this project, so @SimonEnsemble should weigh in here. There is also the `pymatgen`-dependent `primitive_cell`.  

Open to ideas on how to fix this up.  A few of my own to get started:
1. Split python-dependent code into a separate package.  
2. Replace the python deps with Julia ones.
3. Change `runtests.jl` to skip python-dependent code by default.

**Comment by eahenle** [comment]
To clarify: those python-dependent functions are not key elements of `Xtals`.  The "standard" bonding function `infer_bonds!` is not dependent on python, and `primitive_cell` is a convenient but not fundamental feature of the package.

**Comment by eahenle** [comment]
Going with option 1 until option 2 can be done.  `XtalsPyTools` will contain python-dependent tools/interfaces for working with `Xtals`.
