### ISSUE TITLE
adjust covalent radii

### ISSUE THREAD

**Issue by eahenle** [SimonEnsemble/Xtals.jl#38]
current bonding rules based on cordero covalent radii miss ionic/dative bonds in MOFs, esp. w/ heavy atoms (Ba, I) and metals (Cu, Zn)

- [x] adjust values
- [x] explain adjustment in docs
- [x] don't set `missing` for missing values, just omit them
- [x] coords and box are optional co-kwargs for `make_bonds!` (fix the function signature)
- [x] move logic for detection of bond boundary-crossing to `is_bonded`

**Comment by eahenle** [comment]
using values from [https://pubs.acs.org/doi/10.1021/acs.jpcc.0c04903](https://pubs.acs.org/doi/10.1021/acs.jpcc.0c04903)

**Comment by eahenle** [comment]
- [ ] adjust values
- [ ] don't set `missing` for missing values, just omit them
- [ ] coords and box are optional co-kwargs for `make_bonds!` (fix the function signature)
- [ ] move logic for detection of bond boundary-crossing to `is_bonded`

**Comment by SimonEnsemble** [comment]
attn: @aryandeshwal

@eahenle if it helps here is a .cif for `BACMOH` which Arni mentioned in the SI as needing adjusted Cu bond lengths. I also hv the `.mol` version of it saved from Avogadro. note I replicated this 2x2x2 first, then used avogadro to assign the bonds (Avogadro assigns bonds to this one just fine!).

https://u.pcloud.link/publink/show?code=kZV0y8XZuldch6BPOu0JRKPO1DKlEXQ0K7fX
